name: wedding-share
services:
  wedding-share:
    container_name: WeddingShare
    image: cirx08/wedding_share:1.6.8.1
    ports:
      - target: 5000
        published: ${WEBUI_PORT:-5000}
        protocol: tcp
    environment:
      TZ: $TZ
      TITLE: 'WeddingShare'
      ACCOUNT_OWNER_USERNAME: 'admin'
      ACCOUNT_OWNER_PASSWORD: 'admin'
      ENCRYPTION_KEY: 'ChangeMe'
      ENCRYPTION_SALT: 'ChangeMe'
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/app/config
        target: /app/config
      - type: bind
        source: /DATA/AppData/$AppID/app/wwwroot/uploads
        target: /app/wwwroot/uploads
      - type: bind
        source: /DATA/AppData/$AppID/app/wwwroot/thumbnails
        target: /app/wwwroot/thumbnails
      - type: bind
        source: /DATA/AppData/$AppID/app/wwwroot/custom_resources
        target: /app/wwwroot/custom_resources
    network_mode: bridge
    hostname: wedding-share
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "5000"
          description:
            en_gb: "Web UI Port"
      envs:
        - container: TZ
          description:
            en_gb: "TimeZone"
        - container: TITLE
          description:
            en_gb: "Title to display in headers"
        - container: ACCOUNT_OWNER_USERNAME
          description:
            en_gb: "The primary account username"
        - container: ACCOUNT_OWNER_PASSWORD
          description:
            en_gb: "The primary account password"
        - container: ENCRYPTION_KEY
          description:
            en_gb: "The key used to encrypt data"
        - container: ENCRYPTION_SALT
          description:
            en_gb: "The salt used to randomize the encryption"
      volumes:
        - container: /app/config
          description:
            en_gb: "Path to store configuration settings"
        - container: /app/wwwroot/uploads
          description:
            en_gb: "Path to store uploaded content"
        - container: /app/wwwroot/thumbnails
          description:
            en_gb: "Path to store generated thumbnails"
        - container: /app/wwwroot/custom_resources
          description:
            en_gb: "Path to store uploaded logos and banners"
x-casaos:
  main: wedding-share
  architectures:
    - amd64
    - arm
    - arm64
  author: Cirx08
  category: Gallery
  description:
    en_gb: |
      WeddingShare is a very basic site with only one goal. It provides you and your guests a way to share memories of and leading up to the big day. Simply provide your guests with a link to a gallery either via a Url or even better by printing out the provided QR code and dropping it on your guests' dinner tables. Doing so will allow them to view your journey up to this point such as dress/suit shopping, viewing the venue, doing the food tasting or cake shopping, etc.

      You are not limited to a single gallery. You can generate multiple galleries all with their own sharable links. At this stage galleries are a bit unsecure, meaning anyone with the link has access to view and share images so I recommend keeping your share links private. To combat strangers gaining access to your galleries you can provide a secret key during setup but be advised this is a deterrent to make guessing Urls slightly harder and not an actual security catch all.

      Thank you to everyone that supports this project. For anyone that hasn't yet I would be grateful if you would show some support by "buying me a coffee" through the link below. Weddings are expensive and all proceeds from this project will be going towards paying off my wedding bills.

      BuyMeACoffee - https://buymeacoffee.com/cirx08
      GitHub Sponsors - https://github.com/sponsors/Cirx08
  developer: Cirx08
  icon: https://cdn.jsdelivr.net/gh/Cirx08/CasaOS-AppStore@main/Apps/WeddingShare/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cirx08/CasaOS-AppStore@main/Apps/WeddingShare/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/Cirx08/CasaOS-AppStore@main/Apps/WeddingShare/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/Cirx08/CasaOS-AppStore@main/Apps/WeddingShare/screenshot-3.jpg
    - https://cdn.jsdelivr.net/gh/Cirx08/CasaOS-AppStore@main/Apps/WeddingShare/screenshot-4.jpg
  tagline:
    en_gb: A place for guests to view and drop pictures of the big day
  thumbnail: https://cdn.jsdelivr.net/gh/Cirx08/CasaOS-AppStore@main/Apps/WeddingShare/thumbnail.png
  tips: {}
  title:
    en_gb: WeddingShare
  index: /
  port_map: ${WEBUI_PORT:-5000}
